# 一些视频流的处理方法

In [1]:
import cv2
import numpy as np
import os
import glob

In [4]:
s00 = cv2.VideoCapture(0)
s01 = cv2.VideoCapture(1)
s02 = cv2.VideoCapture(2)
s03 = cv2.VideoCapture(3)

In [5]:
while 1:
    ret0, frame0 = s00.read()
    cv2.imshow("capture0", frame0)
    if cv2.waitKey(1) & 0xff == ord('q'):
        break
    if cv2.waitKey(1) & 0xff == ord('0'):
        s0 = s00
        break
    if cv2.waitKey(1) & 0xff == ord('1'):
        s1 = s00
        break
    if cv2.waitKey(1) & 0xff == ord('2'):
        s2 = s00
        break
    if cv2.waitKey(1) & 0xff == ord('3'):
        s3 = s00
        break
s00.release()
cv2.destroyAllWindows()

while 1:
    ret1, frame1 = s01.read()
    cv2.imshow("capture1", frame1)
    if cv2.waitKey(1) & 0xff == ord('q'):
        break
    if cv2.waitKey(1) & 0xff == ord('0'):
        s0 = s01
        break
    if cv2.waitKey(1) & 0xff == ord('1'):
        s1 = s01
        break
    if cv2.waitKey(1) & 0xff == ord('2'):
        s2 = s01
        break
    if cv2.waitKey(1) & 0xff == ord('3'):
        s3 = s01
        break
s01.release()
cv2.destroyAllWindows()

while 1:
    ret2, frame2 = s02.read()
    cv2.imshow("capture2", frame2)
    if cv2.waitKey(1) & 0xff == ord('q'):
        break
    if cv2.waitKey(1) & 0xff == ord('0'):
        s0 = s02
        break
    if cv2.waitKey(1) & 0xff == ord('1'):
        s1 = s02
        break
    if cv2.waitKey(1) & 0xff == ord('2'):
        s2 = s02
        break
    if cv2.waitKey(1) & 0xff == ord('3'):
        s3 = s02
        break
s02.release()
cv2.destroyAllWindows()

while 1:
    ret3, frame3 = s03.read()
    cv2.imshow("capture3", frame3)
    if cv2.waitKey(1) & 0xff == ord('q'):
        break
    if cv2.waitKey(1) & 0xff == ord('0'):
        s0 = s03
        break
    if cv2.waitKey(1) & 0xff == ord('1'):
        s1 = s03
        break
    if cv2.waitKey(1) & 0xff == ord('2'):
        s2 = s03
        break
    if cv2.waitKey(1) & 0xff == ord('3'):
        s3 = s03
        break
s03.release()
cv2.destroyAllWindows()

In [3]:
s1 = cv2.VideoCapture(1)
s2 = cv2.VideoCapture(2)
s3 = cv2.VideoCapture(3)

In [3]:
while 1:
    ret0, frame0 = s0.read()
    cv2.imshow("capture0", frame0)
    if cv2.waitKey(10) & 0xff == ord('q'):
        break
s0.release()
cv2.destroyAllWindows()

while 1:
    ret1, frame1 = s1.read()
    cv2.imshow("capture1", frame1)
    if cv2.waitKey(10) & 0xff == ord('q'):
        break
s1.release()
cv2.destroyAllWindows()

while 1:
    ret2, frame2 = s2.read()
    cv2.imshow("capture2", frame2)
    if cv2.waitKey(10) & 0xff == ord('q'):
        break
s2.release()
cv2.destroyAllWindows()

while 1:
    if s3.isOpened()
        ret3, frame3 = s3.read()
        cv2.imshow("capture3", frame3)
        if cv2.waitKey(10) & 0xff == ord('q'):
            break
s3.release()
cv2.destroyAllWindows()

error: OpenCV(4.5.4) D:\a\opencv-python\opencv-python\opencv\modules\imgproc\src\color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cv::cvtColor'


In [ ]:
while 1:
    ret0, frame0 = s0.read()
    cv2.imshow("capture0", frame0)
    if cv2.waitKey(10) & (0xff == ord('0') | 0xff == ord('1') | 0xff == ord('2') | 0xff == ord('3')):
        if 0xff == ord('0'):
            s0 = s0
        if 0xff == ord('1'):
            s1 = s0
        if 0xff == ord('2'):
            s2 = s0
        if 0xff == ord('3'):
            s3 = s0
        break
s0.release()
cv2.destroyAllWindows()

## 一个窗口下多视频

In [ ]:
width = (int(s1.get(cv2.CAP_PROP_FRAME_WIDTH)))
height = (int(s1.get(cv2.CAP_PROP_FRAME_HEIGHT)))
 
while (s1.isOpened()):
    ret1, frame1 =s1.read()
    ret2, frame2 =s2.read()
    ret3, frame3 =s3.read()
 
    frame1 = cv2.resize(frame1, (int(width), int(height)), interpolation=cv2.INTER_CUBIC)
    frame2 = cv2.resize(frame1, (int(width), int(height)), interpolation=cv2.INTER_CUBIC)
    frame3 = cv2.resize(frame1, (int(width), int(height)), interpolation=cv2.INTER_CUBIC)
 
    frame = np.hstack((frame1, frame2))
 
    cv2.imshow('frame', frame)
    print('111')
    if cv2.waitKey(10) & 0xff == ord('q'):
        break
        
s1.release()
s2.release()
s3.release()

111
111


In [6]:
success,frame=s1.read()
print(frame.shape)
print(frame.size)
print(frame.dtype)

(480, 640, 3)
921600
uint8


In [7]:
frame=frame[0:480,80:560]
print(frame.shape)

(480, 480, 3)


In [8]:
success,frame=s2.read()
print(frame.shape)
print(frame.size)
print(frame.dtype)

AttributeError: 'NoneType' object has no attribute 'shape'

In [ ]:
frame=frame[0:480,80:560]
print(frame.shape)

In [13]:
def cv_show(name,img):
    cv2.imshow(name,img) 
    cv2.waitKey(0) 
    cv2.destroyAllWindows()

In [14]:
cv_show('frame',frame)

## 定时截图

In [8]:
s1 = cv2.VideoCapture(1)
s2 = cv2.VideoCapture(2)
s3 = cv2.VideoCapture(3)
s1.set(3,1920)
s2.set(3,1920)
s3.set(3,1920)
s1.set(4,1080)
s2.set(4,1080)
s3.set(4,1080)

True

In [9]:
def dingshijietu(camera,n,saveLocation):
    index = 0
    imgname = 0

    if not os.path.exists(saveLocation):
        os.makedirs(saveLocation)

    while True:
        index = index +1
        ret, frame = camera.read()
        if index == 1:   # 50ms加一次
            cv2.imshow("capture2", frame)
            imgname = imgname + 1
            fname = str(imgname) + '.jpg'  # fname为图像名字，将imgname作为编号命名保存的截图
            cv2.imwrite(saveLocation+str(n)+"_"+fname, frame) # 截图 前面为放在桌面的路径 img为此时的图像
            print(fname + ' saved')   # 打印保存成功
            index = 0   # 清零
        if imgname >= 10: # 最多截图15张
                break
        # 延时50ms实际相当于获取20帧的图像
        if cv2.waitKey(50) & 0xff == ord('q'):
            break

    # 释放资源
    camera.release()
    cv2.destroyAllWindows()

In [10]:
saveLocation1=r'D:/imageStitching/12.17/camera1/'
saveLocation2=r'D:/imageStitching/12.17/camera2/'
saveLocation3=r'D:/imageStitching/12.17/camera3/'
saveLocation=[saveLocation1,saveLocation2,saveLocation3]
s=[s1,s2,s3]
for index in range(3):
    dingshijietu(s[index],index+1,saveLocation[index])

1.jpg saved
2.jpg saved
3.jpg saved
4.jpg saved
5.jpg saved
6.jpg saved
7.jpg saved
8.jpg saved
9.jpg saved
10.jpg saved
1.jpg saved
2.jpg saved
3.jpg saved
4.jpg saved
5.jpg saved
6.jpg saved
7.jpg saved
8.jpg saved
9.jpg saved
10.jpg saved
1.jpg saved
2.jpg saved
3.jpg saved
4.jpg saved
5.jpg saved
6.jpg saved
7.jpg saved
8.jpg saved
9.jpg saved
10.jpg saved


## glob rewrite测试

In [37]:
saveLocation=r'D:/imageStitching/1207/camera1/'
Images=sorted(glob.glob(r"D:/imageStitching/1207/camera1/*.jpg"),key=os.path.getmtime)
imgname = 0
for fname in Images:
    print(fname)
    imgname = imgname + 1
    img = cv2.imread(fname)
    file_name = os.path.basename(fname)
    cv2.imwrite(saveLocation+file_name+"_rewrited"+'.jpg', img)

## 批量重命名

In [13]:
path =r"D:/imageStitching/tobeCalibratedImages_1213/camera2/"
num= 1
for file in os.listdir(path):
    os.rename(os.path.join(path,file),os.path.join(path,"2_"+str(num)+".jpg"))
    num+=1

In [35]:
DIM = []
K = []
D = []
CAMERA_COUNT = 3  # 摄像头个数
for index in range(1,CAMERA_COUNT+1):
    print(index)
    DIM.append(np.load(r"D:/大四上/传感器/全景拼接/data/DIM" + str(index) + ".npy"))
    K.append(np.load(r"D:/大四上/传感器/全景拼接/data/K" + str(index) + ".npy"))
    D.append(np.load(r"D:/大四上/传感器/全景拼接/data/D" + str(index) + ".npy"))

1
2
3


In [36]:
for index in range(CAMERA_COUNT):
    print(index)
    print(DIM[index])
    print(K[index])
    print(D[index])

0
[480 480]
[[160.81101317   0.         242.33570829]
 [  0.         161.04777673 236.6130631 ]
 [  0.           0.           1.        ]]
[[-0.02645596]
 [-0.0436199 ]
 [ 0.05812316]
 [-0.0234397 ]]
1
[480 480]
[[159.60370542   0.         225.59037695]
 [  0.         159.9038378  232.02681161]
 [  0.           0.           1.        ]]
[[-0.02560749]
 [-0.01602974]
 [ 0.0165772 ]
 [-0.00605274]]
2
[480 480]
[[163.76812015   0.         239.09298896]
 [  0.         163.97747475 236.92056073]
 [  0.           0.           1.        ]]
[[-0.04342591]
 [-0.00203962]
 [ 0.00455834]
 [-0.00200315]]


NameError: name 'biaoding1' is not defined

### 图片集去畸变